export const START_FETCH_PLACES = 'START_FETCH_PLACES'
export const SUCCESS_FETCH_PLACES = 'SUCCESS_FETCH_PLACES'
export const ERROR_FETCH_PLACES = 'ERROR_FETCH_PLACES'

export const START_FETCH_INVENTORY = 'START_FETCH_INVENTORY'
export const SUCCESS_FETCH_INVENTORY = 'SUCCESS_FETCH_INVENTORY'
export const ERROR_FETCH_INVENTORY = 'ERROR_FETCH_INVENTORY'

export const SET_CURRENT_INVENTORY = 'SET_CURRENT_INVENTORY'
export const SET_CURRENT_PLACE = 'SET_CURRENT_PLACE'

export const SET_CHILDREN_PLACE_WITH_HAS_INVENTORY = 'SET_CHILDREN_PLACE_WITH_HAS_INVENTORY'

export const ALL_PLACE_ID_WITH_HAS_INVENTORY= 'ALL_PLACE_ID_WITH_HAS_INVENTORY'